TARGET := ZBox_Housekeeper
 
INCLUDE:= -I ../include
 
LIBS:= -L ../lib/arm -lmosquitto -lcurl -lssl -lcrypto -lpthread -lm
 
CSRCS := $(wildcard *.c)
OBJS := $(patsubst %.c, %.o, $(CSRCS))
 
$(TARGET): $(OBJS) 
	$(CC) $+ -o $@  $(LIBS)
	cp $(TARGET) ../bin -rf
%.o:%.c
	arm-oe-linux-gnueabi-gcc -march=armv7-a -mfloat-abi=softfp -mfpu=neon -c -g -DARM_EC20 $< -o $@ $(INCLUDE)
 
clean:
	rm -rf $(OBJS) $(TARGET) ../bin/$(TARGET)
	#rm *.o
