TARGET := dev_remote_upgrade
 
INCLUDE:= -I ../include
 
LIBS:= -L ../lib/arm -lmosquitto -lcurl -lm
 
CSRCS := $(wildcard *.c)
OBJS := $(patsubst %.c, %.o, $(CSRCS))
 
$(TARGET): $(OBJS) 
	$(CC) $+ -o $@  $(LIBS)
	cp $(TARGET) ../bin -rf
%.o:%.c
	$(CC) -c -g $< -o $@ $(INCLUDE)
 
clean:
	rm -rf $(OBJS) $(TARGET)
	#rm *.o
